INSERT INTO users (name, email, password, user_role) VALUES('ADMIN', 'admin@tienda.es', '37cnkHHeKWnW4RHILsaxLQ==:Fhxj4Xl4X71xEKGxqCofIPcdn/de2ki5fGyxUdL0wT8=', 'ADMIN')
INSERT INTO users (name, email, password, user_role) VALUES('USER', 'usuario@gmail.com', '37cnkHHeKWnW4RHILsaxLQ==:Fhxj4Xl4X71xEKGxqCofIPcdn/de2ki5fGyxUdL0wT8=', 'USER')
INSERT INTO category (name) VALUES('Llantas')
INSERT INTO category (name) VALUES('Cubiertas')
INSERT INTO category (name) VALUES('Manillar')
INSERT INTO category (name) VALUES('Cadena')
INSERT INTO category (name) VALUES('Cassette')
INSERT INTO category (name) VALUES('Plato')
INSERT INTO category (name) VALUES('Desviador')
INSERT INTO category (name) VALUES('Maneta de freno')
INSERT INTO category (name) VALUES('Maneta de cambio')
INSERT INTO category (name) VALUES('Sillín')
INSERT INTO category (name) VALUES('Tija')
INSERT INTO category (name) VALUES('Cuadro')
INSERT INTO category (name) VALUES('Baterías')
INSERT INTO product (descripcion, name, price, stock, category_id) VALUES('Para quienes siempre se esfuerzan por mejorar, la XRC 1200 SPLINE es tu billete a la cima. Experimenta una aceleración mejorada y una agilidad perfeccionada para ponerte a la cabeza. Una técnica de vanguardia para la máxima compresión de la capa de carbono se traduce en nuestras llantas de MTB más ligeras hasta la fecha. Ambas ruedas llevan 24 radios DT revolite. Con una llanta más ligera en la rueda delantera para aumentar la agilidad y nuestro buje para MTB más ligero en la rueda trasera, es nuestro conjunto de ruedas para Cross Country definitivo. La XRC 1200 SPLINE rompe todos los esquemas de tu conjunto para Cross Country favorito. Ahora es tu turno de batir récords.','Llantas DT SWISS XRC 1200 SPLINE',2500.0,6,1)

